---
title: "Onderzoek naar de correlatie tussen leeftijd en schoenmaat"
output: html_document
author: 'Jort, Mathijs, Adib, Bram'
date: '24/4/2023'
---

### Onderzoeksvraag

 

Is er een verschil in schoenmaat tussen verschillende sexe

 

### hypothese

 

Er is bij de mens een sexe-verschil in schoenmaat, we gaan uit van een kleinere schoenmaat bij vrouwen.


### nulhypothese



Er is geen verschil in schoenmaat tussen mannen en vrouwen.



### experiment
Ons plan om ons onderzoeksvraag te beantwoorden van is er een verschil in schoenmaat bij mensen met een sexeverschil. Dit beantwoorden we door 20 mannen en 20 vrouwen te vragen wat hun schoenmaat is.

 

### Protocol

 

### Benodigheden
1. stem
2. vraag

 

### Data verzamelen

 

We zoeken samen met ons groepje uit de klas, in of rond het schoolgebouw medestudenten. We vragen deze medestudenten beleefd of ze willen participeren in een klein wetenschappelijk onderzoekje voor school waarbij de maten van de schoen en leeftijd zullen worden opgenomen.
Is het antwoord nee, dan groet je vriendelijk en zoek je verder.
Is het antwoord ja, dan vragen we de proefpersoon zijn of haar schoenmaat en leeftijd. Deze leggen we vast in onze spreadsheet, samen met een laborant-ID van de proefpersoon. Ten slotte vragen we aan de proefpersoon zijn/haar sexe en leggen wij deze vast. Wil de proefpersoon deze niet geven, of is die nonbinair, dan leggen we dit vast als “anders/onbekend”. Tot slot bedanken we de proefpersoon voor hun deelname.
Wissel de metingen af tussen de verschillende studenten in jouw groepje.

 

We gaan door totdat van ten minste 40 proefpersonen de gegevens zijn verzameld.

```{r visualize, echo = FALSE}
library(ggplot2)

# Load the data
biometric_data <- read.table(file = "schoenmaat.csv",
                             header = TRUE,
                             sep = ",")
 
# Create a scatterplot of Schoenmaat vs. Leeftijd
ggplot(biometric_data, aes(x = Leeftijd, y = Schoenmaat)) +
  geom_point() +
  stat_summary(aes(group = Leeftijd), fun = mean, geom = "point", size = 3, color = "red") +
  labs(x = "Leeftijd", y = "Schoenmaat", title = "Schoenmaat vs. Leeftijd")
```
